name: deloy test

on:
  push:
    branches:
      - test-deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build & Deploy
        env:
          HOSTNAME: ${{secrets.ESC_IP}}
          USER_NAME: ${{secrets.ESC_USER}}
          PRIVATE_KEY: ${{ secrets.YIIRAN8080_RSA }}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            cd ~/home/workspace/FengshuiLayout/ ;
            echo '------ cd done ------' ;
            git checkout test-deploy
            git checkout .
            git pull origin test-deploy
            echo '------ git pull done ------' ;
            docker rm $(docker stop $(docker ps -a -q --filter ancestor=huashuiai-web-docker))
            echo '------ docker rm done ------' ;
            docker build -t huashuiai-web-docker .
            echo '------ docker build done ------'
            docker run -d -p 3000:3000 huashuiai-web-docker
            echo '------ docker run done ------' ;
          '
      - name: success
        run: echo "deploy success"
