name: deloy test ec2
 
on:
   push:
     branches:
       - test-deploy
 
jobs:
   deploy:
     runs-on: ubuntu-latest
     steps:
       - name: create key file
         run: |
           echo "${{secrets.FENGSHUI_PEM}}" > key.pem
           chmod 400 key.pem
       - name: deploy
         run: ssh -i key.pem ec2-user@${{secrets.EC2_IP}} "
             cd ~/home/workspace/FengShuiLayout/
             git checkout test-deploy
             git checkout .
             git pull origin test-deploy
             echo '------ git pull done ------' ;
             docker rm $(docker stop $(docker ps -a -q --filter ancestor=huashuiai-web-docker))
             docker build -t fengshui-web-docker .
             echo '------ docker build done ------'
             docker run -d -p 3000:3000 fengshui-web-docker
             echo '------ docker run done ------' ;
           "
       - name: del key file
         run: rm -rf key.pem
       - name: success
         run: echo "deploy success"